# official gcc image, based on debian, see https://hub.docker.com/_/gcc/
image: gcc

stages:
  - build
  - test
  - test_coverage

before_script:
  - apt-get update && apt-get -y install cmake numdiff
  - export LD_LIBRARY_PATH="$PWD/build/lib:$LD_LIBRARY_PATH"

build:
  stage: build
  script:
    - mkdir build
    - cmake -S . -D CMAKE_INSTALL_PREFIX:PATH=./build -D DEST:STRING=optimized -D VERSION_FROM_GIT:BOOL=ON -D BUILD_TESTING:BOOL=ON -D BUILD_TESTING_WITH_COVERAGE:BOOL=ON
    - make
    - make install
  artifacts:
    paths:
      - build
      - tests

meteo_reading_interpol:
  stage: test
  script:
    - cd tests/meteo_reading_interpol
    - ./meteo_reading_int

meteo_reading_no_interpol:
  stage: test
  script:
    - cd tests/meteo_reading_no_interpol
    - ./meteo_reading_no_int

dataEditing:
  stage: test
  script:
    - cd tests/dataEditing
    - ./data_editing

sun:
  stage: test
  script:
    - cd tests/sun
    - ./sun
    - numdiff -r 1e-4 ref_output.txt curr_output.txt

dem_reading:
  stage: test
  script:
    - cd tests/dem_reading
    - ./dem_reading

2D_interpolations:
  stage: test
  script:
    - cd tests/2D_interpolations
    - ./2D_interpolations 2009-01-19T12:00

arrays:
  stage: test
  script:
    - cd tests/arrays
    - ./arrays

coords:
  stage: test
  script:
    - cd tests/coords
    - ./coordinates

stats:
  stage: test
  script:
    - cd tests/stats
    - ./stats

test_coverage:
  stage: test_coverage
  script:
    - ctest && ctest -D NightlyCoverage