default:
  image: gcc # official gcc image, based on debian, see https://hub.docker.com/_/gcc/
  before_script:
  - apt-get update && apt-get -y install cmake numdiff
  - export LD_LIBRARY_PATH="$PWD/lib:$LD_LIBRARY_PATH"

stages:
  - build
  - test
  - test_coverage
  - release_build
  - release

build:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -S .. -B . -D DEST:STRING=safe -D VERSION_FROM_GIT:BOOL=ON -D BUILD_TESTING:BOOL=ON -D BUILD_TESTING_WITH_COVERAGE:BOOL=ON -D USE_LTO_OPTIMIZATIONS:BOOL=OFF -D METEOIO_TIMESERIES:BOOL=OFF -D CPACK_BUNDLE_ALL:BOOL=ON
    - make -j 2
    # cleanup and compress to avoid limits in GitLab
    - find . -name "*.o" -type f -delete
    - cd .. && tar -czvf build.tar.gz build lib
  artifacts:
    expire_in: 1h
    paths:
      - build.tar.gz

meteo_reading_interpol:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/meteo_reading_interpol
    - ./meteo_reading_int

meteo_reading_no_interpol:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/meteo_reading_no_interpol
    - ./meteo_reading_no_int

dataEditing:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/dataEditing
    - ./data_editing

sun:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/sun
    - ./sun
    - numdiff -r 1e-4 ref_output.txt curr_output.txt

dem_reading:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/dem_reading
    - ./dem_reading

2D_interpolations:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/2D_interpolations
    - ./2D_interpolations 2009-01-19T12:00

arrays:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/arrays
    - ./arrays

coords:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/coords
    - ./coordinates

stats:
  stage: test
  script:
    - tar -xzvf build.tar.gz
    - cp -r tests build
    - cd build/tests/stats
    - ./stats

running times and coverage:
  stage: test_coverage
  script:
    - tar -xzvf build.tar.gz # unpack the built test files and the necessary files for ctest
    - cp -r tests build # copy the required test files into the tests folder
    - cd build
    - ctest && ctest -D NightlyCoverage

release build:
  stage: release_build
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created manually
  dependencies: []
  script:
    - apt-get -y install doxygen graphviz # both doxygen and graphviz are required for cmake "FindDoxygen"
    - mkdir MeteoIO-${CI_COMMIT_TAG#*-}
    - cmake -S . -B . -D CMAKE_INSTALL_PREFIX:PATH=./MeteoIO-${CI_COMMIT_TAG#*-} -D DEST:STRING=safe -D VERSION_FROM_GIT:BOOL=ON -D BUILD_TESTING:BOOL=OFF -D USE_LTO_OPTIMIZATIONS:BOOL=ON -D INSTALL_DOC:BOOL=ON -D CPACK_BUNDLE_ALL:BOOL=ON
    - make -j 2
    - make doc
    - make install
    - tar -czvf ${CI_COMMIT_TAG}.tar.gz MeteoIO-${CI_COMMIT_TAG#*-}
  artifacts:
    expire_in: 1h
    paths:
      - ${CI_COMMIT_TAG}.tar.gz

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script: # overrides global before_script
    - apk add --no-cache curl
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created manually
  dependencies:
    - release build
  script:
    - echo "Uploading ${CI_COMMIT_TAG}.tar.gz to ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/meteoio/${CI_COMMIT_TAG#*-}/${CI_COMMIT_TAG}.tar.gz"
    - 'curl -i --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${CI_COMMIT_TAG}.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/meteoio/${CI_COMMIT_TAG#*-}/${CI_COMMIT_TAG}.tar.gz"'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using GitLab CI/CD'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Linux binary tarball'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/meteoio/${CI_COMMIT_TAG#*-}/${CI_COMMIT_TAG}.tar.gz'
          link_type: 'other'