# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir build
    - cmake -S . -D CMAKE_INSTALL_PREFIX:PATH=./build -D DEST:STRING=optimized -D VERSION_FROM_GIT:BOOL=ON
    - make
    - make install
  artifacts:
    paths:
      - build
      - tests

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt -y install numdiff
    - export LD_LIBRARY_PATH="$PWD/build/lib:$LD_LIBRARY_PATH"
  script:
    - cd tests/sun
    - ./sun.sh

